version: "3.8"

services:
  client:
    image: node:18.7.0-slim
    restart: always
    user: "1000:1000"
    tty: true
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./todo-client:/app
    networks:
      - dev-todo-net

  rest:
    image: maven:3.9-eclipse-temurin-17-alpine
    restart: always
    user: "1000:1000"
    entrypoint: ["sh"]
    tty: true
    ports:
      - 8081:8081
    working_dir: /app
    volumes:
      - ./todo-rest:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev-todo-net

  db:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    networks:
      - dev-todo-net

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev-todo-net

volumes:
  dev-db-data:
networks:
  dev-todo-net:
