- name: Setup Docker
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
    - name: Ensure dependencies are installed.
      apt:
        update_cache: yes
        pkg:
          - ca-certificates
          - gnupg
          - curl
    - name: Ensure Docker APT key is added
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
    - name: Add Docker repository.
      apt_repository:
        update_cache: true
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    - name: Ensure Docker is installed
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
    - name: Ensure Docker service is enabled and restarted
      systemd:
        name: docker
        state: restarted
        enabled: yes
    - name: Ensure Docker users are added to the docker group
      user:
        name: vagrant
        groups: docker
        append: true